python train_vanila_VAE.py -lt 50
python train_vanila_VAE.py -lt 70
python train_vanila_VAE.py -lt 100
python train_vanila_VAE.py -lt 120
python train_vanila_VAE.py -lt 150
python train_custom_VAE.py -lt 70
python train_custom_VAE.py -lt 100
python train_custom_VAE.py -lt 120
python train_batch_VAE.py -lt 70 
python train_batch_VAE.py -lt 100
python train_batch_VAE.py -lt 120  